environment:

  PYTHONPATH: "%APPVEYOR_BUILD_FOLDER%"

  matrix:

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install pytest
  - pip install pyblish-base

build: off

test_script:
  - "%CMD_IN_ENV% pytest"
